import pandas as pd

configfile: "config/config.yaml"

datasets = pd.read_csv("config/datasets.tsv", sep="\t")
samples = list(datasets.loc[:, "sample"].unique())
datasets.set_index("sample", inplace = True)

raw_data = config["raw_data_directory"]
results = config["results_directory"]


def get_brmets_mats(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_matrix.mtx",
    sample = hugo_files)


def get_brmets_features(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_features.tsv",
    sample = hugo_files)


def get_brmets_barcodes(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_barcodes.tsv",
    sample = hugo_files)

def get_brmets_annotation(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_Cell_Types_Annotations.csv",
    sample = hugo_files)


def get_resource(rule, resource):
    try:
        return config["resources"][rule][resource]
    except KeyError:
        return config["resources"]["default"][resource]

   
rule all:
    input:
        f"{results}/seurat/raw/brmets_hugo_gonzalez.rds",
        f"{results}/seurat/raw/pancancer_dalia_barkley.rds",
        f"{results}/seurat/raw/breast_sunny_wu.rds",
        f"{results}/seurat/raw/luad_kim_nayoung.rds",
        f"{results}/seurat/raw/pancancer_sunny_wu.rds",
        f"{results}/seurat/raw/urothelial_chen.rds",
        f"{results}/seurat/raw/adrenalnb_rui_chong.rds",
        f"{results}/seurat/raw/luad_philip_bisschof.rds",
        f"{results}/seurat/raw/pdac_junya_peng.rds",
        f"{results}/seurat/raw/synovial_jerby_arnon.rds",
        f"{results}/seurat/raw/rcell_kevin_bi.rds",
        f"{results}/seurat/raw/pancancer_junbin_qian.rds",


rule sc_brmets_hugo_gonzalez_seurat:
    input:
        mats = get_brmets_mats,
        features = get_brmets_features,
        barcodes = get_brmets_barcodes,
        annotations = get_brmets_annotation,
    output:
        seurat_list = f"{results}/seurat/raw/brmets_hugo_gonzalez.rds",
    threads: get_resource("defaults", "threads")
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    conda:
        "envs/seurat.yaml"
    script:
        "scripts/brmets_hugo_gonzalez_seurat.R"

rule bc_brmets_hugo_gonzalez:
    input:
        seurat_list = rules.sc_brmets_hugo_gonzalez_seurat.output.seurat_list,
    output:
        malignant_list = f"{raw_data}/seurat/malignant/brmets_hugo_gonzalez.rds",
        bc_list = f"{raw_data}/beyondcell/brmets_hugo_gonzalez.rds",
        report = f"{raw_data}/reports/cells_brmets_hugo_gonzalez.tsv",
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    conda:
        "envs/beyondcell.yaml",
    script:
        "scripts/brmets_hugo_gonzalez_beyondcell.R"

rule sc_pancancer_dalia_barkley_seurat:
    input:
        object_list = f"{raw_data}/pancancer_dalia_barkley/srt.list.primary.all.RData",
    output:
        seurat_list = f"{results}/seurat/raw/pancancer_dalia_barkley.rds"
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/pancancer_dalia_barkley_seurat.R"

rule bc_pancancer_dalia_barkley:
    input:
        seurat_list = rules.sc_pancancer_dalia_barkley_seurat.output.seurat_list,
    output:
        malignant_list = f"{raw_data}/seurat/malignant/pancancer_dalia_barkley.rds",
        bc_list = f"{raw_data}/beyondcell/pancancer_dalia_barkley.rds",
        report = f"{raw_data}/reports/pancancer_dalia_barkley.tsv",
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    conda:
        "envs/beyondcell.yaml",
    script:
        "scripts/pancancer_dalia_barkley_beyondcell.R"

rule sc_breast_sunny_wu_seurat:
    input:
        mat = f"{raw_data}/breast_sunny_wu/matrix.mtx.gz",
        barcodes = f"{raw_data}/breast_sunny_wu/barcodes.tsv.gz",
        features = f"{raw_data}/breast_sunny_wu/features.tsv.gz",
        metadata = f"{raw_data}/breast_sunny_wu/metadata.csv",
    output:
        seurat_list = f"{results}/seurat/raw/breast_sunny_wu.rds",
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb = get_resource("defaults", "mem_mb"),
        walltime = get_resource("defaults", "walltime"),
    params:
        data_dir = f"{raw_data}/breast_sunny_wu",
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/breast_sunny_wu_seurat.R"


rule sc_pancancer_sunny_wu_seurat:
    input:
        mat = f"{raw_data}/pancancer_sunny_wu/matrix.mtx.gz",
        barcodes = f"{raw_data}/pancancer_sunny_wu/barcodes.tsv.gz",
        features = f"{raw_data}/pancancer_sunny_wu/features.tsv.gz",
        metadata = f"{raw_data}/pancancer_sunny_wu/Wu_etal_2021_metadata.txt",
    output:
        seurat_list = f"{results}/seurat/raw/pancancer_sunny_wu.rds",
    threads: 
        get_resource("defaults", "threads"),
    resources:
        mem_mb = get_resource("defaults", "mem_mb"),
        walltime = get_resource("defaults", "walltime"),
    params:
        data_dir = f"{raw_data}/pancancer_sunny_wu",
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/pancancer_sunny_wu_seurat.R"


rule sc_luad_kim_nayoung_seurat:
    input:
        mat_object = f"{raw_data}/luad_kim_nayoung/GSE131907_Lung_Cancer_raw_UMI_matrix.rds",
        annotations = f"{raw_data}/luad_kim_nayoung/GSE131907_Lung_Cancer_cell_annotation.txt",
    output:
        seurat_list = f"{results}/seurat/raw/luad_kim_nayoung.rds",
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb = get_resource("defaults", "mem_mb"),
        walltime = get_resource("defaults", "walltime"),
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/luad_kim_nayoung_seurat.R"


rule sc_urothelial_chen_seurat:
    input:
        object_list = f"{raw_data}/urothelial_chen/sc_Chen_BUC.rda",
    output:
        seurat_list = f"{results}/seurat/raw/urothelial_chen.rds"
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/urothelial_chen_seurat.R"


rule sc_adrenalnb_rui_chong_seurat:
    input:
        object_list = f"{raw_data}/adrenalnb_rui_chong/human_NB_subset_tumor.rda",
        tumor_data = f"{raw_data}/adrenalnb_rui_chong/tumor_dataset_annotation.csv",
        gland_data = f"{raw_data}/adrenalnb_rui_chong/adrenal_gland_annotation.csv",
        reference_gene_annotation = "/storage/scratch01/shared/projects/bc-meta/reference/hgnc_gene_with_protein_product_2023-03-22.tsv",

    output:
        seurat_list = f"{results}/seurat/raw/adrenalnb_rui_chong.rds"
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/adrenalnb_rui_chong_seurat.R"


rule sc_luad_philip_bisschof_seurat:
    input:
        metadata = f"{raw_data}/luad_philip_bisschof/patients_metadata.xlsx",
        infercnv_scores = f"{raw_data}/luad_philip_bisschof/infercnv_clone_scores_nsclc.tsv",
    output:
        seurat_list = f"{results}/seurat/raw/luad_philip_bisschof.rds"
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    params:
        data_dir = f"{raw_data}/luad_philip_bisschof",
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/luad_philip_bisschof_seurat.R"


rule sc_pdac_junya_peng_seurat:
    input:
        object_list = f"{raw_data}/pdac_junya_peng/pdac_junya_peng.RData",
        celltype = f"{raw_data}/pdac_junya_peng/all_celltype.txt",
    output:
        seurat_list = f"{results}/seurat/raw/pdac_junya_peng.rds"
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=144000,
        walltime=get_resource("defaults", "walltime"),
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/pdac_junya_peng_seurat.R"


rule sc_synovial_jerby_arnon_seurat:
    input:
        object_list = f"{raw_data}/synovial_jerby_arnon/seurat_pre-qc.rds",
    output:
        seurat_list = f"{results}/seurat/raw/synovial_jerby_arnon.rds"
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/synovial_jerby_arnon_seurat.R"


rule sc_rcell_kevin_bi_seurat:
    input:
        metadata = f"{raw_data}/rcell_kevin_bi/Final_SCP_Metadata.txt",
    output:
        seurat_list = f"{results}/seurat/raw/rcell_kevin_bi.rds"
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    params:
        data_dir = f"{raw_data}/rcell_kevin_bi",
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/rcell_kevin_bi_seurat.R"


rule sc_pancancer_junbin_qian_seurat:    
    output:
        seurat_list = f"{results}/seurat/raw/pancancer_junbin_qian.rds"
    threads: get_resource("defaults", "threads"),
    resources:
        mem_mb=get_resource("defaults", "mem_mb"),
        walltime=get_resource("defaults", "walltime"),
    params:
        data_dir = f"{raw_data}/pancancer_junbin_qian",
    conda:
        "envs/seurat.yaml",
    script:
        "scripts/pancancer_junbin_qian_seurat.R"