import pandas as pd


configfile: "config/config.yaml"


datasets = pd.read_csv("config/datasets.tsv", sep="\t")
samples = list(datasets.loc[:, "sample"].unique())
datasets.set_index("sample", inplace=True)

raw_data = config["raw_data_directory"]
results = config["results_directory"]


def get_brmets_mats(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(
        f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_matrix.mtx", sample=hugo_files
    )


def get_brmets_features(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(
        f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_features.tsv", sample=hugo_files
    )


def get_brmets_barcodes(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(
        f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_barcodes.tsv", sample=hugo_files
    )


def get_brmets_annotation(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(
        f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_Cell_Types_Annotations.csv",
        sample=hugo_files,
    )


def get_resource(rule, resource):
    try:
        return config["resources"][rule][resource]
    except KeyError:
        return config["resources"]["default"][resource]


rule all:
    input:
        f"{results}/reports/cells_brmets_hugo_gonzalez.tsv",
        f"{results}/reports/cells_pancancer_dalia_barkley.tsv",
        f"{results}/reports/cells_breast_sunny_wu.tsv",
        f"{results}/reports/cells_pancancer_sunny_wu.tsv",
        f"{results}/reports/cells_luad_kim_nayoung.tsv",
        f"{results}/reports/cells_urothelial_chen.tsv",
        f"{results}/reports/cells_adrenalnb_rui_chong.tsv",
        f"{results}/reports/cells_luad_philip_bisschof.tsv",
        f"{results}/reports/cells_pancancer_junbin_qian.tsv",
        f"{results}/reports/cells_aml_audrey_lasry.tsv",
        f"{results}/reports/cells_cll_ramon_massoni.tsv",
        f"{results}/reports/cells_gbm_nourhan_abdelfattah.tsv",
        f"{results}/reports/cells_synovial_jerby_arnon.tsv",
        f"{results}/reports/cells_pdac_junya_peng.tsv",
        f"{results}/reports/cells_cc_xiaosong_lu.tsv",
        f"{results}/reports/cells_rcell_kevin_bi.tsv",
        f"{results}/reports/cells_rcell_r_li.tsv",
        f"{results}/reports/cells_pleural_rui_dong.tsv",
        f"{results}/reports/cells_bone_yun_liu.tsv",
        f"{results}/reports/cells_mmieloma_stephan_tirier.tsv",
        f"{results}/reports/cells_all_maxime_caron.tsv",
        f"{results}/reports/cells_cells_crc_lei_zhang.tsv",
        f"{results}/reports/cells_florian_uhlitz.tsv",


include: "rules/preprocessing.smk"
include: "rules/beyondcell.smk"
