import pandas as pd


configfile: "config/config.yaml"


datasets = pd.read_csv("config/datasets.tsv", sep="\t")
samples = list(datasets.loc[:, "sample"].unique())
datasets.set_index("sample", inplace=True)

raw_data = config["raw_data_directory"]
results = config["results_directory"]


def get_brmets_mats(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(
        f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_matrix.mtx", sample=hugo_files
    )


def get_brmets_features(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(
        f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_features.rds", sample=hugo_files
    )


def get_brmets_barcodes(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(
        f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_barcodes.rds", sample=hugo_files
    )


def get_brmets_annotation(wc):
    hugo_files = datasets.loc[datasets["study"] == "brmets_hugo_gonzalez", "filename"]

    return expand(
        f"{raw_data}/brmets_hugo_gonzalez/{{sample}}_Cell_Types_Annotations.csv",
        sample=hugo_files,
    )


def get_resource(rule, resource):
    try:
        return config["resources"][rule][resource]
    except KeyError:
        return config["resources"]["default"][resource]


rule all:
    input:
        f"{results}/functional/brmets_hugo_gonzalez.rds",
        f"{results}/functional/pancancer_dalia_barkley.rds",
        f"{results}/functional/breast_sunny_wu.rds",
        f"{results}/functional/pancancer_sunny_wu.rds",
        f"{results}/functional/luad_kim_nayoung.rds",
        f"{results}/functional/urothelial_chen.rds",
        f"{results}/functional/adrenalnb_rui_chong.rds",
        f"{results}/functional/luad_philip_bisschof.rds",
        f"{results}/functional/pancancer_junbin_qian.rds",
        f"{results}/functional/aml_audrey_lasry.rds",
        f"{results}/functional/cll_ramon_massoni.rds",
        f"{results}/functional/gbm_nourhan_abdelfattah.rds",
        f"{results}/functional/synovial_jerby_arnon.rds",
        f"{results}/functional/pdac_junya_peng.rds",
        f"{results}/functional/cc_xiaosong_lu.rds",
        f"{results}/functional/rcell_kevin_bi.rds",
        f"{results}/functional/rcell_r_li.rds",
        f"{results}/functional/pleural_rui_dong.rds",
        f"{results}/functional/bone_yun_liu.rds",
        f"{results}/functional/mmieloma_stephan_tirier.rds",
        f"{results}/functional/all_maxime_caron.rds",
        f"{results}/functional/crc_florian_uhlitz.rds",
        f"{results}/functional/bcc_catherine_dyao.rds",
        f"{results}/functional/uvm_michael_durante.rds",
        f"{results}/functional/esca_xiannian_zhang.rds",
        f"{results}/functional/brca_bhupinder_pal.rds",
        f"{results}/functional/prad_sujun_chen.rds",
        f"{results}/functional/chol_min_zhang.rds",
        f"{results}/functional/skcm_chao_zhang.rds",
        f"{results}/functional/brmets_jana_biermann.rds"

include: "rules/preprocessing.smk"
include: "rules/beyondcell.smk"
include: "rules/functional.smk"
