import scanpy as sc
import pandas as pd
import numpy as np
import os

# Set working directory.
os.chdir("/storage/scratch01/shared/projects/bc-meta/single_cell/seurat/tcca/")

mapping = {"Stromal cell": ["Adipocyte", 
                            "CAF",
                            "Chondrocyte",
                            "iCAF", 
                            "MSC", 
                            "myCAF", 
                            "Osteoblast",
                            "Pericyte", 
                            "PVL", 
                            "SMC", 
                            "Stellate",
                            # Platelets lack platelet markers and express stromal markers instead
                            "Megakaryocyte", 
                            "Platelet"],
            "Glial cell": ["Astrocyte",
                            "Enteric_glia",
                            "Oligodendrocyte",
                            "OPC",
                            "Schwann"],
            "Epithelial": ["Acinar",
                           "AT1",
                           "AT2",
                           "Barretts",
                           "Basal",
                           "Cholangiocyte",
                           "Club",
                           "Ductal",
                           "Langerhan",
                           "Epithelial",
                           "Epithelial_dividing",
                           "Globet",
                           "Hepatocyte",
                           "Ionocyte",
                           "Keratinocyte",
                           "Mesothelial",
                           "Multiciliated",
                           "Myoepithelial",
                           "Neuroendocrine",
                           "SMG",
                           "Squamous",
                           "Tuft"],
            "B-cell": ["B",
                       "B_dividing",
                       "B_f",
                       "B_gc",
                       "B_malt",
                       "B_mature",
                       "B_memory",
                       "B_naive",
                       "B_pre",
                       "B_pro",
                       "B_transitional"],
            "Dendritic cell": ["ASDC",
                               "cDC_mature",
                               "cDC1",
                               "cDC2",
                               "DC",
                               "FDC",
                               "pre_cDC"],
            "Plasmacytoid dendritic cell": ["pDC", 
                                            "pre_pDC"],
            "Endothelial": ["Endometrial_endometrial",
                            "Endothelial",
                            "Endothelial_arterial",
                            "Endothelial_capillary",
                            "Endothelial_lymphatic",
                            "Endothelial_stalk",
                            "Endothelial_tip",
                            "Endothelial_venous",
                            "EPC"],
            "Erythrocyte": ["Erythrocyte", "Erythroblast"],
            "Granulocyte": ["Basophil",
                            "Granulocyte",
                            "Neutrophil",
                            "Myelocyte"],
            "Mast": ["Mast"],
            "Monocyte/Macrophage": ["Mo", 
                                    "Mp", 
                                    "Mp_dividing"],
            "NK cell": ["NK"],
            "Neuron": ["L2/3 IT",
                       "L5 IT",
                       "L5/6 NP",
                       "L6 IT",
                       "L6 IT Car3",
                       "L6b",
                       "Lamp5",
                       "Neuron", 
                       "Pvalb",
                       "Sncg",
                       "Sst",
                       "Vip"],
            "Stem": ["ASPC", 
                     "BMCP", 
                     "CLP", 
                     "CMP", 
                     "ESC",
                     "GMP",
                     "HPC",
                     "HSC",
                     "HSPC",
                     "IPS",
                     "LMPP",
                     "MEP",
                     "MPP",
                     "Neuroepithelial",
                     "TSC"],
            "Innate lymphoid cells": ["ILC"],
            "Plasma cell": ["Plasma",
                            "Plasma_dividing",
                            "Plasma_IgA",
                            "Plasma_IgG",
                            "Plasma_IgM",
                            "Plasmablast"],
            "CD4+ T-cell": ["CD4T",
                            "CD4T_dividing",
                            "CD4Tcm",
                            "CD4Teff",
                            "CD4Tfh",
                            "CD4Tfhex",
                            "CD4Tn",
                            "Th17"],
            "CD8+ T-cell": ["CD8T",
                            "CD8T_dividing",
                            "CD8Tcm",
                            "CD8Teff",
                            "CD8Teff_41BBhi",
                            "CD8Teff_41BBlo",
                            "CD8Tem",
                            "CD8Tex",
                            "CD8Tn",
                            "CD8Trm"],
            "Regulatory T-cell": ["Treg"],
            "Unconventional T-cells": ["T",
                                       "dnT",
                                       "dpT",
                                       "gdT",
                                       "MAIT",
                                       "NKT"], 
            "Malignant": ["Malignant"],
            "Unknown":["unknown"]
}
   
metadata = pd.read_csv("tcca_metadata.tsv", sep = "\t")
metadata["cell_type_main"] = metadata["cell_type_main"].replace({"malignant": "Malignant"})
metadata["cell_type_fine"] = metadata["cell_type_fine"].replace({"malignant": "Malignant"})

# Create a reverse mapping
reverse_mapping = {subtype: key for key, subtypes in mapping.items() for subtype in subtypes}

# Define a lambda function to map values, while handling NaN values
def map_cell_type(row):
    if pd.notna(row["cell_type_fine"]):
        return reverse_mapping.get(row["cell_type_fine"], "Unknown")
    else:
        return reverse_mapping.get(row["cell_type_main"], "Unknown")

metadata["cell_type_broad"] =  metadata.apply(map_cell_type, axis=1)
ordered_columns = metadata.columns.values[0:29].tolist() + ["cell_type_broad"] + 
    metadata.columns.values[29:metadata.shape[1]].tolist()
metadata = metadata[ordered_columns]

metadata.to_csv("tcca_metadata.tsv", sep = "\t", index = False)
